type EnvDefinition = Record<string, { comment: string; exampleValue?: string }>

/**
 * Please run `pnpm run env:example` to generate `.env.example` file after updated the env
 */
export const ENV_DEFINITIONS = {
	_: {
		comment:
			"This file is autogenerated via `pnpm run env:example` (scripts/generate-env-example.ts), please do not edit it manually.",
	},

	DATABASE_URL: {
		exampleValue: `postgresql://\${username}:\${password}@blablabla.your-db-link.oho/papa?sslmode=require`,
		comment:
			"Link to your PostgreSQL database, use pooled connection if you deploy on a serverless platform",
	},

	VITE_TURNSTILE_SITE_KEY: {
		exampleValue: "",
		comment: "Turnstile site key that expose to client",
	},

	TURNSTILE_SECRET_KEY: {
		exampleValue: "",
		comment:
			"Secret key should not expose with VITE_, only access on the server. Keys got from Cloudfare Turnstile",
	},

	AUTH_SECRET: {
		exampleValue: "",
		comment:
			"Auth Secret Key, generate with `node -e \"console.log(require('crypto').randomBytes(16).toString('hex'))\"`",
	},

	VITE_BASE_URL: {
		exampleValue: "http://localhost:5173",
		comment:
			"Base URL of your website, with VITE prefix will expose to both server and client",
	},

	APP_NAME: {
		exampleValue: "",
		comment: "What your app name is",
	},

	EMAIL_PROVIDER: {
		exampleValue: "smtp",
		comment: "Email provider; Options: 'smtp', 'nodemailer', 'ses', 'resend'",
	},
	EMAIL_FROM: {
		exampleValue: "Name <sys@example.com>",
		comment: "Email address to send emails from, must be verified",
	},

	RESEND_API_KEY: { exampleValue: "re_blablabla", comment: "Email: Resend" },

	SMTP_HOST: {
		exampleValue: "smtp.resend.com",
		comment: "Email: Nodemailer(SMTP)",
	},
	SMTP_PORT: {
		exampleValue: "465",
		comment: "Email: Nodemailer(SMTP)",
	},
	SMTP_SECURE: {
		exampleValue: "true",
		comment:
			"Email: Nodemailer(SMTP); Set to true if using port 465 (SSL), false for 587 port (encrypted/TLS, default)",
	},
	SMTP_USER: {
		exampleValue: "resend",
		comment: "Email: Nodemailer(SMTP)",
	},
	SMTP_PASS: {
		exampleValue: "re_blablabla",
		comment: "Email: Nodemailer(SMTP)",
	},

	AWS_SES_REGION: {
		exampleValue: "",
		comment: "Email: AWS SES",
	},
	AWS_SES_ACCESS_KEY_ID: {
		exampleValue: "",
		comment: "Email: AWS SES",
	},
	AWS_SES_SECRET_ACCESS_KEY: {
		exampleValue: "",
		comment: "Email: AWS SES",
	},

	BUCKET_NAME: {
		exampleValue: "",
		comment:
			"Object Storage; Please set up a bucket and provide its name here. Default to 'papa' if null (which means your bucket should also be named 'papa')",
	},
	OBJECT_STORAGE_ACCESS_KEY_ID: { exampleValue: "", comment: "Object Storage" },
	OBJECT_STORAGE_SECRET_ACCESS_KEY: {
		exampleValue: "",
		comment: "Object Storage",
	},
	OBJECT_STORAGE_ACCOUNT_ID: { exampleValue: "", comment: "Object Storage" },
} as const satisfies EnvDefinition

export type EnvKey = Exclude<keyof typeof ENV_DEFINITIONS, "_">

/**
 * @return `string` server environment variable through `process.env`
 */
export const getEnv = <T extends EnvKey>(env: T): string => {
	if (typeof process === "undefined") {
		throw new Error(
			"getEnv can only be used in server environment, use import.meta.env.VITE_XXX for client env",
		)
	}

	return process.env[env] || ""
}
