import { relations } from 'drizzle-orm'
import {
    boolean,
    integer,
    pgTable,
    serial,
    timestamp,
    varchar,
} from 'drizzle-orm/pg-core'
import { posts } from './posts'

export const seos = pgTable('seos', {
    id: serial('id').primaryKey(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at')
        .notNull()
        .defaultNow()
        .$onUpdate(() => new Date()),
    metaTitle: varchar('meta_title', { length: 255 }),
    metaDescription: varchar('meta_description', { length: 255 }),
    autoGenerated: boolean('auto_generated').notNull(),
    route: varchar('route', { length: 255 }),

    postId: integer('post_id')
        .unique()
        .references(() => posts.id, { onDelete: 'cascade' }),
})

export const seosRelations = relations(seos, ({ one }) => ({
    post: one(posts, { fields: [seos.postId], references: [posts.id] }),
}))
