import type { Route } from './+types'
import { useEffect, useRef, useState } from 'react'
import { useFetcher } from 'react-router'

import { type ColumnDef, type Table } from '@tanstack/react-table'
import { PlusCircle } from 'lucide-react'

import { Button } from '~/components/ui/button'
import { DropdownMenuItem } from '~/components/ui/dropdown-menu'
import { useFetcherNotification } from '~/hooks/use-notification'
import { getSEOs } from '~/lib/db/seo.server'
import { DashboardDataTableMoreMenu } from '~/routes/papa/dashboard/components/dashboard-data-table'
import {
	DashboardActions,
	DashboardContent,
	DashboardHeader,
	DashboardLayout,
	DashboardTitle,
} from '~/routes/papa/dashboard/components/dashboard-wrapper'
import { SeoContent } from '~/routes/papa/dashboard/components/seo-content'

import { DashboardDataTable } from '../components/dashboard-data-table'
import { useSkipper } from '../components/dashboard-data-table/hooks'

export const loader = async () => {
	const { seos } = await getSEOs()
	return { seos }
}

export type SeoLoaderType = Awaited<ReturnType<typeof loader>>['seos'][number]

export default function SEO({ loaderData }: Route.ComponentProps) {
	const [open, setOpen] = useState(false)

	const tableRef = useRef<Table<SeoLoaderType>>(null)
	const [shouldSkip, skip] = useSkipper()
	const [state, setState] = useState(loaderData.seos)

	useEffect(() => {
		skip()
		setState(loaderData.seos)
	}, [loaderData])

	return (
		<DashboardLayout>
			<DashboardHeader>
				<DashboardTitle
					title="SEO"
					description="Used by either post or route. Post will auto-generate one when created. If you customize a route, make sure to use this source to create meta data."
				/>
				<DashboardActions>
					<Button size={'sm'} onClick={() => setOpen(true)}>
						<PlusCircle />
						<p className="text-xs">Create seo</p>
					</Button>
					<SeoContent
						method="POST"
						action={`/dashboard/seo/resource`}
						open={open}
						setOpen={setOpen}
					/>
				</DashboardActions>
			</DashboardHeader>
			<DashboardContent className="px-0 md:px-0">
				<DashboardDataTable
					columns={columns}
					data={state}
					setData={setState}
					ref={tableRef}
					autoResetPageIndex={shouldSkip}
					skipAutoResetPageIndex={skip}
					className="px-2 md:px-3"
					initialPageSize={20}
				></DashboardDataTable>
			</DashboardContent>
		</DashboardLayout>
	)
}

export const columns: ColumnDef<SeoLoaderType>[] = [
	{
		accessorKey: 'route',
		header: 'Route',
	},
	{
		accessorKey: 'metaTitle',
		header: 'Title',
	},
	{
		accessorKey: 'description',
		header: 'Description',
		cell: ({ row }) => {
			return (
				<div className="py-2">
					<p className="line-clamp-3 text-sm break-words whitespace-normal">
						{row.original.metaDescription || '-'}
					</p>
				</div>
			)
		},
	},
	{
		accessorKey: 'autoGenerated',
		header: 'Auto Generated',
		accessorFn: row => (row.autoGenerated ? 'Yes' : 'No'),
	},
	{
		accessorKey: 'createdAt',
		header: 'Created at',
		cell: ({ row }) => row.original.createdAt.toLocaleString('zh-TW'),
	},
	{
		accessorKey: 'updatedAt',
		header: 'Updated At',
		cell: ({ row }) => row.original.updatedAt.toLocaleString('zh-TW'),
	},
	{
		id: '_actions',
		cell: ({ row }) => {
			const fetcher = useFetcher()
			const { mutating } = useFetcherNotification(fetcher)

			const rowId = row.id
			const [open, setOpen] = useState(false)
			const id = row.original.id
			const deleteTarget = row.original.metaTitle ?? undefined

			useEffect(() => {
				if (mutating) {
					// row.original.setRowsDeleting(prev => {
					// 	const newSet = new Set(prev)
					// 	newSet.add(rowId)
					// 	return newSet
					// })
				} else {
					// row.original.setRowsDeleting(prev => {
					// 	const newSet = new Set(prev)
					// 	newSet.delete(rowId)
					// 	return newSet
					// })
				}
			}, [mutating])

			return (
				<>
					<DashboardDataTableMoreMenu
						id={id}
						deletable={!row.original.autoGenerated}
						deleteTarget={deleteTarget}
						onDelete={() => {
							fetcher.submit(
								{ id },
								{
									method: 'DELETE',
									action: `/dashboard/seo/resource`,
								},
							)
						}}
					>
						<DropdownMenuItem onClick={() => setOpen(true)}>
							Edit
						</DropdownMenuItem>
					</DashboardDataTableMoreMenu>
					<SeoContent
						method="PUT"
						action={`/dashboard/seo/resource`}
						seo={row.original}
						open={open}
						setOpen={setOpen}
					/>
				</>
			)
		},
	},
]
