import type { Route } from './+types/route'
import { useEffect } from 'react'
import { type ShouldRevalidateFunctionArgs } from 'react-router'

import { useSetAtom } from 'jotai'
import { useHydrateAtoms } from 'jotai/utils'

import {
	getCrossSellProducts,
	getProduct,
	getProductGallery,
	getUpsellProducts,
} from '../../../lib/db/product.server'
import {
	crossSellProductsAtom,
	isResolvingAtom,
	productAtom,
	productGalleryAtom,
	upsellProductsAtom,
	type Product,
} from '../../../store/product/context'
import { ProductEditPage } from './page'

export const loader = async ({ params }: Route.LoaderArgs) => {
	if (params.productSlug === 'new') {
		return {
			product: newProduct(),
			productGalleryPromise: Promise.resolve([]),
			crossSellProductsPromise: Promise.resolve([]),
			upsellProductsPromise: Promise.resolve([]),
		}
	}

	const product = await getProduct({
		slug: params.productSlug,
		edit: true,
	})

	if (!product) {
		throw new Response('Product Not Found', { status: 404 })
	}

	const productGalleryPromise = getProductGallery(product.id)
	const crossSellProductsPromise = getCrossSellProducts(product.id)
	const upsellProductsPromise = getUpsellProducts(product.id)

	return {
		product,
		productGalleryPromise,
		crossSellProductsPromise,
		upsellProductsPromise,
	}
}

// To prevent revalidation when fetchers are called (taxonomies, brands, etc.)
// Please call revalidate() manually when updating product
// To prevent revalidation when fetchers are called (taxonomies, brands, etc.)
// Please call revalidate() manually when updating product
export const shouldRevalidate = ({
	currentUrl,
	currentParams,
	nextParams,
	formAction,
}: ShouldRevalidateFunctionArgs) => {
	// POST, PUT, DELETE
	if (formAction === `${new URL(currentUrl).pathname}/resource`) return true

	// GET
	if (currentParams !== nextParams) {
		return true
	} else {
		return false
	}
}

export default function ECProduct({ loaderData }: Route.ComponentProps) {
	useHydrateAtoms([[productAtom, loaderData.product]])
	const setProduct = useSetAtom(productAtom)
	const setIsResolving = useSetAtom(isResolvingAtom)
	const setProductGallery = useSetAtom(productGalleryAtom)
	const setCrossSellProducts = useSetAtom(crossSellProductsAtom)
	const setUpsellProducts = useSetAtom(upsellProductsAtom)

	useEffect(() => {
		setProduct(loaderData.product)
		setIsResolving({
			crossSellProducts: true,
			productGallery: true,
		})

		// Resolve promises
		loaderData.productGalleryPromise
			.then(setProductGallery)
			.finally(() => setIsResolving(r => ({ ...r, productGallery: false })))
		loaderData.crossSellProductsPromise
			.then(setCrossSellProducts)
			.finally(() => setIsResolving(r => ({ ...r, crossSellProducts: false })))
		loaderData.upsellProductsPromise
			.then(setUpsellProducts)
			.finally(() => setIsResolving(r => ({ ...r, upsellProducts: false })))

		return () => {
			setProduct(null)
			setIsResolving({ crossSellProducts: false, productGallery: false })
			setCrossSellProducts([])
			setProductGallery([])
		}
	}, [loaderData])

	return <ProductEditPage />
}

const newProduct = (): NonNullable<Product> => {
	const now = new Date()

	return {
		id: -1,
		status: 'DRAFT',
		slug: `new-product-${now.getTime()}`,
		name: 'New Product',
		subtitle: null,
		description: null,
		instructions: [],
		purchaseNote: null,
		productOptionId: -1,
		visibility: 'PUBLIC',
		password: null,
		lang: 'en',
		authorId: null,
		seoId: -1,
		publishedAt: null as unknown as Date,
		createdAt: now,
		updatedAt: now,
		deletedAt: null as unknown as Date,
		option: {
			id: -1,
			active: 1,
			image: null,
			imageAlt: null,
			imageTitle: null,
			price: 0n,
			salePrice: 0n,
			saleStartsAt: null as unknown as Date,
			saleEndsAt: null as unknown as Date,
			currency: 'USD',
			scale: 2,
			minQtyAllowed: 1,
			maxQtyAllowed: null,
			step: 1,
			downloadable: 0,
			downloadFiles: [],
			downloadLimit: null,
			downloadExpiry: null,
			sku: null,
			identifier: null,
			manageStock: 0,
			stockStatus: 'inStock',
			virtual: 0,
			weight: null,
			dimension: { length: 0, width: 0, height: 0 },
			note: null,
			createdAt: now,
			updatedAt: now,
		},
		categories: [],
		tags: [],
		brands: [],
		variants: [],
		attributes: [],
		seo: {
			id: -1,
			metaTitle: null,
			metaDescription: null,
			keywords: null,
			ogImage: null,
			autoGenerated: false,
			route: null,
			createdAt: now,
			updatedAt: now,
		},
	}
}
