import type { Route } from './+types'
import { useEffect, useRef, useState } from 'react'
import { useFetcher } from 'react-router'

import { PlusCircleIcon } from '@phosphor-icons/react'
import { type ColumnDef, type Table } from '@tanstack/react-table'

import { Button } from '~/components/ui/button'
import { DropdownMenuItem } from '~/components/ui/dropdown-menu'
import {
	DashboardDataTable,
	DashboardDataTableMoreMenu,
} from '~/components/dashboard/dashboard-data-table'
import { useSkipper } from '~/components/dashboard/dashboard-data-table/hooks'
import {
	DashboardActions,
	DashboardContent,
	DashboardHeader,
	DashboardLayout,
	DashboardTitle,
} from '~/components/dashboard/dashboard-wrapper'
import { useFetcherNotification } from '~/hooks/use-notification'
import type { Seo } from '~/lib/db/schema'
import { SeoDialog } from '~/routes/dashboard/seo/seo-content'

export { action, loader } from './resource'

export default function SEO({ loaderData }: Route.ComponentProps) {
	const fetcher = useFetcher()
	const { isSubmitting } = useFetcherNotification(fetcher)

	const [open, setOpen] = useState(false)

	const tableRef = useRef<Table<Seo>>(null)
	const [shouldSkip, skip] = useSkipper()
	const [state, setState] = useState(loaderData.seos)

	useEffect(() => {
		skip()
		setState(loaderData.seos)
	}, [loaderData])

	return (
		<DashboardLayout>
			<DashboardHeader>
				<DashboardTitle
					title="SEO"
					description="Unified place to overview and manage site SEO settings."
				/>
				<DashboardActions>
					<Button size={'sm'} onClick={() => setOpen(true)}>
						<PlusCircleIcon />
						<p className="text-xs">Create seo</p>
					</Button>
					<SeoDialog
						open={open}
						onOpenChange={setOpen}
						isCreate
						onSave={s =>
							fetcher.submit(JSON.stringify(s), {
								method: 'POST',
								encType: 'application/json',
							})
						}
						isSaving={isSubmitting}
					/>
				</DashboardActions>
			</DashboardHeader>
			<DashboardContent className="px-0 md:px-0">
				<DashboardDataTable
					columns={columns}
					data={state}
					setData={setState}
					getRowId={r => r.id.toString()}
					ref={tableRef}
					autoResetPageIndex={shouldSkip}
					skipAutoResetPageIndex={skip}
					className="px-2 md:px-3"
					initialPageSize={20}
				/>
			</DashboardContent>
		</DashboardLayout>
	)
}

export const columns: ColumnDef<Seo>[] = [
	{
		accessorKey: 'route',
		header: 'Route',
	},
	{
		accessorKey: 'metaTitle',
		header: 'Title',
	},
	{
		accessorKey: 'metaDescription',
		header: 'Description',
		cell: ({ row }) => {
			return (
				<div className="py-2">
					<p className="line-clamp-3 text-sm break-words whitespace-normal">
						{row.original.metaDescription || '-'}
					</p>
				</div>
			)
		},
	},
	{
		accessorKey: 'autoGenerated',
		header: 'System',
		accessorFn: row => (row.autoGenerated ? 'Yes' : 'No'),
	},
	{
		accessorKey: 'createdAt',
		header: 'Created at',
		cell: ({ row }) => row.original.createdAt.toLocaleString('zh-TW'),
	},
	{
		accessorKey: 'updatedAt',
		header: 'Updated At',
		cell: ({ row }) => row.original.updatedAt.toLocaleString('zh-TW'),
	},
	{
		id: '_actions',
		cell: ({ row }) => {
			const fetcher = useFetcher()
			const { isSubmitting } = useFetcherNotification(fetcher)

			const [open, setOpen] = useState(false)
			const id = row.original.id
			const deleteTarget = row.original.metaTitle ?? undefined

			return (
				<>
					<DashboardDataTableMoreMenu
						id={id}
						deletable={!row.original.autoGenerated}
						deleteTarget={deleteTarget}
						onDelete={() => {
							fetcher.submit(
								{ id },
								{
									method: 'DELETE',
									encType: 'application/json',
								},
							)
						}}
					>
						<DropdownMenuItem
							onClick={() => {
								setOpen(true)
								console.log('row', row.original)
							}}
						>
							Edit
						</DropdownMenuItem>
					</DashboardDataTableMoreMenu>
					<SeoDialog
						seo={row.original}
						open={open}
						onOpenChange={setOpen}
						isCreate={false}
						onSave={s =>
							fetcher.submit(JSON.stringify(s), {
								method: 'PUT',
								encType: 'application/json',
							})
						}
						isSaving={isSubmitting}
					/>
				</>
			)
		},
	},
]
