import type { Route } from './+types'

import { z } from 'zod'

import { createSeo, deleteSeo, getSeos, updateSeo } from '~/lib/db/seo.server'
import { type ActionResponse } from '~/lib/utils'
import { handleError } from '~/lib/utils/server'

const insertSchmea = z.object({
	metaTitle: z.string().nullable(),
	metaDescription: z.string().nullable(),
	keywords: z.string().nullable(),
	route: z.string().nullable(),
	ogImage: z.string().nullable(),
})

const updateSchmea = insertSchmea.extend({
	id: z.number(),
})

const deleteSchema = z.object({
	id: z.number(),
})

export const action = async ({ request }: Route.ActionArgs) => {
	if (!['POST', 'PUT', 'DELETE'].includes(request.method)) {
		return {
			err: 'Method not allowed',
		} satisfies ActionResponse
	}

	console.log('action')

	const seoRequested = await request.json()

	switch (request.method) {
		case 'POST':
			try {
				const seoToCreate = insertSchmea.parse(seoRequested)
				const seo = await createSeo({
					metaTitle: seoToCreate.metaTitle,
					metaDescription: seoToCreate.metaDescription,
					route: seoToCreate.route,
					keywords: seoToCreate.keywords,
					ogImage: seoToCreate.ogImage,
					autoGenerated: false,
				})
				return {
					msg: `SEO for ${seo.route || seo.metaTitle || 'unknown'} created`,
				} satisfies ActionResponse
			} catch (error) {
				return handleError(error, request)
			}
		case 'PUT':
			try {
				const seoToUpdate = updateSchmea.parse(seoRequested)
				const seo = await updateSeo({
					id: seoToUpdate.id,
					metaTitle: seoToUpdate.metaTitle,
					metaDescription: seoToUpdate.metaDescription,
					route: seoToUpdate.route,
					keywords: seoToUpdate.keywords,
					ogImage: seoToUpdate.ogImage,
				})
				return {
					msg: `SEO for ${seo.route || seo.metaTitle || 'unknown'} updated`,
				} satisfies ActionResponse
			} catch (error) {
				return handleError(error, request)
			}
		case 'DELETE':
			try {
				const { id } = deleteSchema.parse(seoRequested)
				const seo = await deleteSeo(id)
				return {
					msg: `SEO for ${seo.route || seo.metaTitle || 'unknown'} delete`,
				} satisfies ActionResponse
			} catch (error) {
				return handleError(error, request)
			}
	}
}

export const loader = async () => await getSeos()
