import { useState } from 'react'

import { SpinnerIcon } from '@phosphor-icons/react'

import { Button } from '~/components/ui/button'
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from '~/components/ui/dialog'
import { Field, FieldDescription, FieldLabel } from '~/components/ui/field'
import { Input } from '~/components/ui/input'
import { SeoFieldSet } from '~/components/seo-field-set'
import { defaultSeo, type Seo } from '~/lib/db/schema'

export const SeoDialog = ({
	seo = defaultSeo,
	open,
	onOpenChange,
	onSave,
	isSaving = false,
	isCreate = false,
}: {
	seo?: Seo
	open: boolean
	onOpenChange: (open: boolean) => void
	onSave: (seo: Seo) => void
	isSaving?: boolean
	isCreate?: boolean
}) => {
	const [seoState, setSeoState] = useState(seo)
	const handleChange = <K extends keyof Seo>(field: K, value: Seo[K]) => {
		setSeoState(prev => ({ ...prev, [field]: value }))
	}

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className="max-h-[90vh] overflow-scroll sm:max-w-[425px]">
				<DialogHeader>
					<DialogTitle>{isCreate ? 'Create' : 'Edit'} seo</DialogTitle>
					<DialogDescription>
						{isCreate ? 'Create' : 'Make changes to'} your route seo here. Last
						updated on {new Date(seoState.updatedAt).toLocaleString('zh-TW')}
					</DialogDescription>
				</DialogHeader>
				<Field>
					<FieldLabel htmlFor="route">Route</FieldLabel>
					{seoState.autoGenerated ? (
						<>
							<Input readOnly disabled value={seoState.route || ''} />
							<FieldDescription>
								Auto generated seo route cannot be edited.
							</FieldDescription>
						</>
					) : (
						<Input
							id="route"
							name="route"
							type="text"
							placeholder="Enter the route for this SEO entry."
							value={seoState.route || ''}
							onChange={e =>
								seoState.autoGenerated
									? null
									: handleChange('route', e.target.value ?? null)
							}
						/>
					)}
				</Field>
				<SeoFieldSet
					seo={seoState}
					onFillInTitle={() => handleChange('metaTitle', 'meta title')}
					onTitleChange={title => handleChange('metaTitle', title ?? null)}
					onFillInDescription={() =>
						handleChange('metaDescription', 'meta description')
					}
					onDescriptionChange={desc =>
						handleChange('metaDescription', desc ?? null)
					}
					onFillInOgImage={() => handleChange('ogImage', 'og image')}
					onOgImageChange={({ src }) => handleChange('ogImage', src ?? null)}
					onKeywordsChange={keywords =>
						handleChange('keywords', keywords ?? null)
					}
				/>
				<DialogFooter>
					<Button disabled={isSaving} onClick={() => onSave(seoState)}>
						{isSaving && <SpinnerIcon className="animate-spin" />}
						{isCreate ? 'Create' : 'Save'}
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	)
}
